from src.states.calvin import (
    AreaEulerState,
    BoolState,
    FlipState,
    PreciseEulerState,
    QuatState,
    RangeState,
)


_S = {
    "ee_position": PreciseEulerState(
        name="ee_position",
        id=0,
    ),
    "ee_rotation": QuatState(
        name="ee_rotation",
        id=1,
    ),
    "ee_scalar": BoolState(
        name="ee_scalar",
        id=2,
    ),
    "base__slide_position": PreciseEulerState(
        name="base__slide_position",
        id=3,
    ),
    "base__slide_rotation": QuatState(
        name="base__slide_rotation",
        id=4,
    ),
    "base__slide_scalar": RangeState(
        name="base__slide_scalar",
        id=5,
        lower_bound=0.0,
        upper_bound=0.28,
    ),
    "base__drawer_position": PreciseEulerState(
        name="base__drawer_position",
        id=6,
    ),
    "base__drawer_rotation": QuatState(
        name="base__drawer_rotation",
        id=7,
    ),
    "base__drawer_scalar": RangeState(
        name="base__drawer_scalar",
        id=8,
        lower_bound=0.0,
        upper_bound=0.22,
    ),
    "base__button_position": PreciseEulerState(
        name="base__button_position",
        id=9,
    ),
    "base__button_rotation": QuatState(
        name="base__button_rotation",
        id=10,
    ),
    "base__button_scalar": FlipState(
        name="base__button_scalar",
        id=11,
    ),
    "led_position": PreciseEulerState(
        name="led_position",
        id=12,
    ),
    "led_rotation": QuatState(
        name="led_rotation",
        id=13,
    ),
    "block_red_position": AreaEulerState(
        name="block_red_position",
        id=14,
    ),
    "block_red_rotation": QuatState(
        name="block_red_rotation",
        id=15,
        ignore=True,
    ),
    "block_red_scalar": BoolState(
        name="block_red_scalar",
        id=16,
    ),
    "block_blue_position": AreaEulerState(
        name="block_blue_position",
        id=17,
    ),
    "block_blue_rotation": QuatState(
        name="block_blue_rotation",
        id=18,
        ignore=True,
    ),
    "block_blue_scalar": BoolState(
        name="block_blue_scalar",
        id=19,
    ),
    "block_pink_position": AreaEulerState(
        name="block_pink_position",
        id=20,
    ),
    "block_pink_rotation": QuatState(
        name="block_pink_rotation",
        id=21,
        ignore=True,
    ),
    "block_pink_scalar": BoolState(
        name="block_pink_scalar",
        id=22,
    ),
}

STATES_BY_TAG = {
    "Debug": [
        _S["ee_position"],
        _S["base__slide_position"],
        _S["base__drawer_position"],
        _S["base__button_position"],
        _S["led_position"],
        _S["block_red_position"],
        _S["block_blue_position"],
        _S["block_pink_position"],
        _S["ee_rotation"],
        _S["base__slide_rotation"],
        _S["base__drawer_rotation"],
        _S["base__button_rotation"],
        _S["led_rotation"],
        _S["block_red_rotation"],
        _S["block_blue_rotation"],
        _S["block_pink_rotation"],
        _S["ee_scalar"],
        _S["base__slide_scalar"],
        _S["base__drawer_scalar"],
        _S["base__button_scalar"],
        _S["block_red_scalar"],
        _S["block_blue_scalar"],
        _S["block_pink_scalar"],
    ],
    "Base": [
        _S["ee_position"],
        _S["base__slide_position"],
        _S["base__drawer_position"],
        _S["base__button_position"],
        _S["led_position"],
        _S["ee_rotation"],
        _S["base__slide_rotation"],
        _S["base__drawer_rotation"],
        _S["base__button_rotation"],
        _S["led_rotation"],
        _S["ee_scalar"],
        _S["base__slide_scalar"],
        _S["base__drawer_scalar"],
        _S["base__button_scalar"],
    ],
    "SmallRed": [
        _S["ee_position"],
        _S["ee_rotation"],
        _S["ee_scalar"],
        _S["base__drawer_position"],
        _S["base__drawer_rotation"],
        _S["base__drawer_scalar"],
        _S["base__button_position"],
        _S["base__button_rotation"],
        _S["base__button_scalar"],
        _S["led_position"],
        _S["led_rotation"],
        _S["block_red_position"],
        _S["block_red_rotation"],
        _S["block_red_scalar"],
    ],
    "SmallBlue": [
        _S["ee_position"],
        _S["ee_rotation"],
        _S["ee_scalar"],
        _S["base__drawer_position"],
        _S["base__drawer_rotation"],
        _S["base__drawer_scalar"],
        _S["base__button_position"],
        _S["base__button_rotation"],
        _S["base__button_scalar"],
        _S["led_position"],
        _S["led_rotation"],
        _S["block_blue_position"],
        _S["block_blue_rotation"],
        _S["block_blue_scalar"],
    ],
    "SmallPink": [
        _S["ee_position"],
        _S["ee_rotation"],
        _S["ee_scalar"],
        _S["base__drawer_position"],
        _S["base__drawer_rotation"],
        _S["base__drawer_scalar"],
        _S["base__button_position"],
        _S["base__button_rotation"],
        _S["base__button_scalar"],
        _S["led_position"],
        _S["led_rotation"],
        _S["block_pink_position"],
        _S["block_pink_rotation"],
        _S["block_pink_scalar"],
    ],
    "BaseRed": [
        _S["ee_position"],
        _S["ee_rotation"],
        _S["ee_scalar"],
        _S["base__slide_position"],
        _S["base__slide_rotation"],
        _S["base__slide_scalar"],
        _S["base__drawer_position"],
        _S["base__drawer_rotation"],
        _S["base__drawer_scalar"],
        _S["base__button_position"],
        _S["base__button_rotation"],
        _S["base__button_scalar"],
        _S["led_position"],
        _S["led_rotation"],
        _S["block_red_position"],
        _S["block_red_rotation"],
        _S["block_red_scalar"],
    ],
    "BaseRedPink": [
        _S["ee_position"],
        _S["ee_rotation"],
        _S["ee_scalar"],
        _S["base__slide_position"],
        _S["base__slide_rotation"],
        _S["base__slide_scalar"],
        _S["base__drawer_position"],
        _S["base__drawer_rotation"],
        _S["base__drawer_scalar"],
        _S["base__button_position"],
        _S["base__button_rotation"],
        _S["base__button_scalar"],
        _S["led_position"],
        _S["led_rotation"],
        _S["block_red_position"],
        _S["block_red_rotation"],
        _S["block_red_scalar"],
        _S["block_pink_position"],
        _S["block_pink_rotation"],
        _S["block_pink_scalar"],
    ],
    "BaseRedPinkBlue": [
        _S["ee_position"],
        _S["ee_rotation"],
        _S["ee_scalar"],
        _S["base__slide_position"],
        _S["base__slide_rotation"],
        _S["base__slide_scalar"],
        _S["base__drawer_position"],
        _S["base__drawer_rotation"],
        _S["base__drawer_scalar"],
        _S["base__button_position"],
        _S["base__button_rotation"],
        _S["base__button_scalar"],
        _S["led_position"],
        _S["led_rotation"],
        _S["block_red_position"],
        _S["block_red_rotation"],
        _S["block_red_scalar"],
        _S["block_pink_position"],
        _S["block_pink_rotation"],
        _S["block_pink_scalar"],
        _S["block_blue_position"],
        _S["block_blue_rotation"],
        _S["block_blue_scalar"],
    ],
    "BasePink": [
        _S["ee_position"],
        _S["ee_rotation"],
        _S["ee_scalar"],
        _S["base__slide_position"],
        _S["base__slide_rotation"],
        _S["base__slide_scalar"],
        _S["base__drawer_position"],
        _S["base__drawer_rotation"],
        _S["base__drawer_scalar"],
        _S["base__button_position"],
        _S["base__button_rotation"],
        _S["base__button_scalar"],
        _S["led_position"],
        _S["led_rotation"],
        _S["block_pink_position"],
        _S["block_pink_rotation"],
        _S["block_pink_scalar"],
    ],
    "BaseBlue": [
        _S["ee_position"],
        _S["ee_rotation"],
        _S["ee_scalar"],
        _S["base__slide_position"],
        _S["base__slide_rotation"],
        _S["base__slide_scalar"],
        _S["base__drawer_position"],
        _S["base__drawer_rotation"],
        _S["base__drawer_scalar"],
        _S["base__button_position"],
        _S["base__button_rotation"],
        _S["base__button_scalar"],
        _S["led_position"],
        _S["led_rotation"],
        _S["block_blue_position"],
        _S["block_blue_rotation"],
        _S["block_blue_scalar"],
    ],
}
