from src.skills.tapas import TapasSkill

predict_as_batch = True

_S = {
    "CloseDrawer": TapasSkill(
        name="CloseDrawer",
        id=0,
        reversed=False,
        predict_as_batch=predict_as_batch,
        overrides=[],
    ),
    "CloseDrawerBack": TapasSkill(
        name="CloseDrawerBack",
        id=1,
        reversed=True,
        predict_as_batch=predict_as_batch,
        overrides=["ee_scalar", "ee_rotation", "ee_position"],
    ),
    "OpenDrawer": TapasSkill(
        name="OpenDrawer",
        id=2,
        reversed=False,
        predict_as_batch=predict_as_batch,
        overrides=[],
    ),
    "OpenDrawerBack": TapasSkill(
        name="OpenDrawerBack",
        id=3,
        reversed=True,
        predict_as_batch=predict_as_batch,
        overrides=["ee_scalar", "ee_rotation", "ee_position"],
    ),
    "PressButton": TapasSkill(
        name="PressButton",
        id=4,
        reversed=False,
        predict_as_batch=predict_as_batch,
        overrides=[],
    ),
    "PressButtonBack": TapasSkill(
        name="PressButtonBack",
        id=5,
        reversed=True,
        predict_as_batch=predict_as_batch,
        overrides=["ee_scalar", "ee_rotation", "ee_position"],
    ),
    "OpenSlide": TapasSkill(
        name="OpenSlide",
        id=6,
        reversed=False,
        predict_as_batch=predict_as_batch,
        overrides=[],
    ),
    "CloseSlide": TapasSkill(
        name="CloseSlide",
        id=7,
        reversed=False,
        predict_as_batch=predict_as_batch,
        overrides=[],
    ),
    "OpenSlideBack": TapasSkill(
        name="OpenSlideBack",
        id=8,
        reversed=True,
        predict_as_batch=predict_as_batch,
        overrides=["ee_scalar", "ee_rotation", "ee_position"],
    ),
    "CloseSlideBack": TapasSkill(
        name="CloseSlideBack",
        id=9,
        reversed=True,
        predict_as_batch=predict_as_batch,
        overrides=["ee_scalar", "ee_rotation", "ee_position"],
    ),
    "GrabRedTable": TapasSkill(
        name="GrabRedTable",
        id=10,
        reversed=False,
        predict_as_batch=predict_as_batch,
        overrides=[],
    ),
    "PlaceRedTable": TapasSkill(
        name="PlaceRedTable",
        id=11,
        reversed=True,
        predict_as_batch=predict_as_batch,
        overrides=[
            "ee_scalar",
            "ee_rotation",
            "ee_position",
            "block_red_position",
            "block_red_rotation",
            "block_red_scalar",
        ],
    ),
    "GrabRedDrawer": TapasSkill(
        name="GrabRedDrawer",
        id=12,
        reversed=False,
        predict_as_batch=predict_as_batch,
        overrides=[],
    ),
    "PlaceRedDrawer": TapasSkill(
        name="PlaceRedDrawer",
        id=13,
        reversed=True,
        predict_as_batch=predict_as_batch,
        overrides=[
            "ee_scalar",
            "ee_rotation",
            "ee_position",
            "block_red_position",
            "block_red_rotation",
            "block_red_scalar",
        ],
    ),
    "GrabPinkTable": TapasSkill(
        name="GrabPinkTable",
        id=14,
        reversed=False,
        predict_as_batch=predict_as_batch,
        overrides=[],
    ),
    "PlacePinkTable": TapasSkill(
        name="PlacePinkTable",
        id=15,
        reversed=True,
        predict_as_batch=predict_as_batch,
        overrides=[
            "ee_scalar",
            "ee_rotation",
            "ee_position",
            "block_pink_position",
            "block_pink_rotation",
            "block_pink_scalar",
        ],
    ),
    "GrabPinkDrawer": TapasSkill(
        name="GrabPinkDrawer",
        id=16,
        reversed=False,
        predict_as_batch=predict_as_batch,
        overrides=[],
    ),
    "PlacePinkDrawer": TapasSkill(
        name="PlacePinkDrawer",
        id=17,
        reversed=True,
        predict_as_batch=predict_as_batch,
        overrides=[
            "ee_scalar",
            "ee_rotation",
            "ee_position",
            "block_pink_position",
            "block_pink_rotation",
            "block_pink_scalar",
        ],
    ),
    "GrabBlueTable": TapasSkill(
        name="GrabBlueTable",
        id=18,
        reversed=False,
        predict_as_batch=predict_as_batch,
        overrides=[],
    ),
    "GrabBlueDrawer": TapasSkill(
        name="GrabBlueDrawer",
        id=19,
        reversed=False,
        predict_as_batch=predict_as_batch,
        overrides=[],
    ),
    "PlaceBlueTable": TapasSkill(
        name="PlaceBlueTable",
        id=20,
        reversed=True,
        predict_as_batch=predict_as_batch,
        overrides=[
            "ee_scalar",
            "ee_rotation",
            "ee_position",
            "block_blue_position",
            "block_blue_rotation",
            "block_blue_scalar",
        ],
    ),
    "PlaceBlueDrawer": TapasSkill(
        name="PlaceBlueDrawer",
        id=21,
        reversed=True,
        predict_as_batch=predict_as_batch,
        overrides=[
            "ee_scalar",
            "ee_rotation",
            "ee_position",
            "block_blue_position",
            "block_blue_rotation",
            "block_blue_scalar",
        ],
    ),
}

SKILLS_BY_TAG = {
    "Drawer": [
        _S["CloseDrawer"],
        _S["CloseDrawerBack"],
        _S["OpenDrawer"],
        _S["OpenDrawerBack"],
    ],
    "Slide": [
        _S["OpenSlide"],
        _S["OpenSlideBack"],
        _S["CloseSlide"],
        _S["CloseSlideBack"],
    ],
    "Button": [
        _S["PressButton"],
        _S["PressButtonBack"],
    ],
    "Red": [
        _S["GrabRedTable"],
        _S["PlaceRedTable"],
        _S["GrabRedDrawer"],
        _S["PlaceRedDrawer"],
    ],
    "Pink": [
        _S["GrabPinkTable"],
        _S["PlacePinkTable"],
        _S["GrabPinkDrawer"],
        _S["PlacePinkDrawer"],
    ],
    "Blue": [
        _S["GrabBlueTable"],
        _S["PlaceBlueTable"],
        _S["GrabBlueDrawer"],
        _S["PlaceBlueDrawer"],
    ],
    "BaseRed": [
        _S["CloseDrawer"],
        _S["CloseDrawerBack"],
        _S["OpenDrawer"],
        _S["OpenDrawerBack"],
        _S["PressButton"],
        _S["PressButtonBack"],
        _S["OpenSlide"],
        _S["CloseSlide"],
        _S["OpenSlideBack"],
        _S["CloseSlideBack"],
        _S["GrabRedTable"],
        _S["PlaceRedTable"],
        _S["GrabRedDrawer"],
        _S["PlaceRedDrawer"],
    ],
    "BaseRedPink": [
        _S["CloseDrawer"],
        _S["CloseDrawerBack"],
        _S["OpenDrawer"],
        _S["OpenDrawerBack"],
        _S["PressButton"],
        _S["PressButtonBack"],
        _S["OpenSlide"],
        _S["CloseSlide"],
        _S["OpenSlideBack"],
        _S["CloseSlideBack"],
        _S["GrabRedTable"],
        _S["PlaceRedTable"],
        _S["GrabRedDrawer"],
        _S["PlaceRedDrawer"],
        _S["GrabPinkTable"],
        _S["PlacePinkTable"],
        _S["GrabPinkDrawer"],
        _S["PlacePinkDrawer"],
    ],
    "BaseRedPinkBlue": [
        _S["CloseDrawer"],
        _S["CloseDrawerBack"],
        _S["OpenDrawer"],
        _S["OpenDrawerBack"],
        _S["PressButton"],
        _S["PressButtonBack"],
        _S["OpenSlide"],
        _S["CloseSlide"],
        _S["OpenSlideBack"],
        _S["CloseSlideBack"],
        _S["GrabRedTable"],
        _S["PlaceRedTable"],
        _S["GrabRedDrawer"],
        _S["PlaceRedDrawer"],
        _S["GrabPinkTable"],
        _S["PlacePinkTable"],
        _S["GrabPinkDrawer"],
        _S["PlacePinkDrawer"],
        _S["GrabBlueTable"],
        _S["PlaceBlueTable"],
        _S["GrabBlueDrawer"],
        _S["PlaceBlueDrawer"],
    ],
    "BasePink": [
        _S["CloseDrawer"],
        _S["CloseDrawerBack"],
        _S["OpenDrawer"],
        _S["OpenDrawerBack"],
        _S["PressButton"],
        _S["PressButtonBack"],
        _S["OpenSlide"],
        _S["CloseSlide"],
        _S["OpenSlideBack"],
        _S["CloseSlideBack"],
        _S["GrabPinkTable"],
        _S["PlacePinkTable"],
        _S["GrabPinkDrawer"],
        _S["PlacePinkDrawer"],
    ],
    "BaseBlue": [
        _S["CloseDrawer"],
        _S["CloseDrawerBack"],
        _S["OpenDrawer"],
        _S["OpenDrawerBack"],
        _S["PressButton"],
        _S["PressButtonBack"],
        _S["OpenSlide"],
        _S["CloseSlide"],
        _S["OpenSlideBack"],
        _S["CloseSlideBack"],
        _S["GrabBlueTable"],
        _S["PlaceBlueTable"],
        _S["GrabBlueDrawer"],
        _S["PlaceBlueDrawer"],
    ],
    "Debug": [
        _S["CloseDrawer"],
        _S["CloseDrawerBack"],
        _S["OpenDrawer"],
        _S["OpenDrawerBack"],
        _S["PressButton"],
        _S["PressButtonBack"],
        _S["OpenSlide"],
        _S["CloseSlide"],
        _S["OpenSlideBack"],
        _S["CloseSlideBack"],
        _S["GrabRedTable"],
        _S["GrabPinkTable"],
        _S["GrabBlueTable"],
        _S["GrabRedDrawer"],
        _S["GrabPinkDrawer"],
        _S["GrabBlueDrawer"],
        _S["PlaceRedTable"],
        _S["PlacePinkTable"],
        _S["PlaceBlueTable"],
        _S["PlaceRedDrawer"],
        _S["PlacePinkDrawer"],
        _S["PlaceBlueDrawer"],
    ],
    "Normal": [
        _S["CloseDrawer"],
        _S["CloseDrawerBack"],
        _S["OpenDrawer"],
        _S["OpenDrawerBack"],
        _S["PressButton"],
        _S["PressButtonBack"],
        _S["OpenSlide"],
        _S["CloseSlide"],
        _S["OpenSlideBack"],
        _S["CloseSlideBack"],
        _S["GrabRedTable"],
        _S["GrabPinkTable"],
        _S["GrabBlueTable"],
        _S["GrabRedDrawer"],
        _S["GrabPinkDrawer"],
        _S["GrabBlueDrawer"],
        _S["PlaceRedTable"],
        _S["PlacePinkTable"],
        _S["PlaceBlueTable"],
        _S["PlaceRedDrawer"],
        _S["PlacePinkDrawer"],
        _S["PlaceBlueDrawer"],
    ],
    "Minimal": [
        _S["CloseDrawer"],
        _S["CloseDrawerBack"],
        _S["OpenDrawer"],
        _S["OpenDrawerBack"],
        _S["PressButton"],
        _S["PressButtonBack"],
        _S["OpenSlide"],
        _S["CloseSlide"],
        _S["OpenSlideBack"],
        _S["CloseSlideBack"],
    ],
}
