_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 50
                - 53
                - 55
                - 63
                - 77
            "2":
                - 1
                - 5
                - 41
                - 49
                - 50
                - 53
                - 55
                - 63
                - 77
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.10.18
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
nt:
    value: gnn4
p_empty:
    value: 0
p_rand:
    value: 0
state_tag:
    value: Minimal
tag:
    value: t1_pe_0.0_pr_0.0
task_tag:
    value: Minimal
